/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HealthUI;

import Healthmodel.Hospital;
import Healthmodel.HospitalDirectory;
import Healthmodel.Patient;
import Healthmodel.PatientDirectory;
import Healthmodel.Person;
import Healthmodel.PersonDirectory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chava
 */
public class HospitalRegistration extends javax.swing.JFrame {

    /**
     * Creates new form HospitalRegistration
     */
   Hospital hosp = new Hospital();
   HospitalDirectory hospDir;
    public HospitalRegistration(HospitalDirectory hospDir) {
        initComponents();
        this.hospDir=hospDir;
        hospDispTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        hospitalHomeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        hospitalLogoutBtn = new javax.swing.JButton();
        hospitalRegisterBtn = new javax.swing.JButton();
        hospitalUpdateBtn = new javax.swing.JButton();
        hospitalDeleteBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        hospTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        hospitalName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hospitalLicenseNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        hospitalNowards = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        hospitalCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hospitalCommunity = new javax.swing.JTextField();
        hospitalZipCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hospitalAddress = new javax.swing.JTextField();
        hospitalState = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hospitalViewBtn = new javax.swing.JButton();
        hospitalSearch = new javax.swing.JTextField();
        hospitalSearchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        hospitalHomeBtn.setText("Home");
        hospitalHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalHomeBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 15)); // NOI18N
        jLabel1.setText("Hospital Registration");

        hospitalLogoutBtn.setText("Logout");
        hospitalLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalLogoutBtnActionPerformed(evt);
            }
        });

        hospitalRegisterBtn.setText("Register");
        hospitalRegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalRegisterBtnActionPerformed(evt);
            }
        });

        hospitalUpdateBtn.setText("Update");
        hospitalUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalUpdateBtnActionPerformed(evt);
            }
        });

        hospitalDeleteBtn.setText("Delete");
        hospitalDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalDeleteBtnActionPerformed(evt);
            }
        });

        hospTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "License No", "Name", "Address", "Community", "City", "State", "Zip Code", "No of Wards"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(hospTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Hospital Details"));

        jLabel3.setText("License No");

        jLabel2.setText("Name");

        hospitalLicenseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalLicenseNoActionPerformed(evt);
            }
        });

        jLabel9.setText("No. of Wards");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hospitalLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalNowards, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hospitalLicenseNo, hospitalName, hospitalNowards});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hospitalName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalLicenseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalNowards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(0, 0, 0))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Address Details"));

        jLabel6.setText("City");

        jLabel7.setText("Community");

        hospitalCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalCommunityActionPerformed(evt);
            }
        });

        hospitalZipCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalZipCodeActionPerformed(evt);
            }
        });

        jLabel8.setText("Zip Code");

        jLabel4.setText("Address");

        jLabel5.setText("State");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospitalState, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {hospitalAddress, hospitalCity, hospitalCommunity, hospitalState, hospitalZipCode});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hospitalAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(hospitalCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(hospitalCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hospitalState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {hospitalAddress, hospitalCity, hospitalCommunity, hospitalState, hospitalZipCode});

        hospitalViewBtn.setText("View");
        hospitalViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalViewBtnActionPerformed(evt);
            }
        });

        hospitalSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalSearchActionPerformed(evt);
            }
        });

        hospitalSearchBtn.setText("Search");
        hospitalSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 881, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(200, 200, 200)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(195, 195, 195)
                                .addComponent(hospitalRegisterBtn)
                                .addGap(70, 70, 70)
                                .addComponent(hospitalUpdateBtn)
                                .addGap(70, 70, 70)
                                .addComponent(hospitalDeleteBtn)
                                .addGap(70, 70, 70)
                                .addComponent(hospitalViewBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(hospitalHomeBtn)
                                .addGap(329, 329, 329)
                                .addComponent(jLabel1)
                                .addGap(365, 365, 365)
                                .addComponent(hospitalLogoutBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(301, 301, 301)
                                .addComponent(hospitalSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(hospitalSearchBtn)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalHomeBtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(hospitalLogoutBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalUpdateBtn)
                    .addComponent(hospitalDeleteBtn)
                    .addComponent(hospitalRegisterBtn)
                    .addComponent(hospitalViewBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hospitalSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hospitalSearchBtn))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospitalHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalHomeBtnActionPerformed
        // TODO add your handling code here:

        MainFrame newMainFrame = new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_hospitalHomeBtnActionPerformed

    private void hospitalLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalLogoutBtnActionPerformed
        // TODO add your handling code here

        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_hospitalLogoutBtnActionPerformed

    private void hospitalLicenseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalLicenseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalLicenseNoActionPerformed

    private void hospitalCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalCommunityActionPerformed

    private void hospitalZipCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalZipCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalZipCodeActionPerformed

    private void hospitalDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalDeleteBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hospitalDeleteBtnActionPerformed

    private void hospitalViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalViewBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex1=hospTable.getSelectedRow();
        if (selectedRowIndex1<0){
            JOptionPane.showMessageDialog(this,"Please select a row to View");
            return;
        }
        DefaultTableModel model1 = (DefaultTableModel) hospTable.getModel();
        Hospital selectedHosp=(Hospital)model1.getValueAt(selectedRowIndex1,0);
        hospitalName.setText(selectedHosp.getHospName());
        hospitalLicenseNo.setText(String.valueOf(selectedHosp.getHospLicNo()));
        hospitalNowards.setText(String.valueOf(selectedHosp.getHospWard()));
        hospitalZipCode.setText(String.valueOf(selectedHosp.residence.getZip()));
        hospitalCommunity.setText(selectedHosp.residence.getCommunityName());
        hospitalAddress.setText(selectedHosp.getHospAddress());
        hospitalCity.setText(selectedHosp.residence.getNewCity());
        hospitalState.setText(selectedHosp.residence.getState());
    }//GEN-LAST:event_hospitalViewBtnActionPerformed

    private void hospitalRegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalRegisterBtnActionPerformed
        // TODO add your handling code here:
        Hospital hosp=new Hospital();
        hosp.setHospName(hospitalName.getText());
//        pt1.person.setAge(Integer.parseInt(patientAge.getText()));
        hosp.setHospLicNo(Integer.parseInt(hospitalLicenseNo.getText()));
        hosp.setHospAddress((hospitalAddress.getText()));
        hosp.residence.setCommunityName(hospitalCommunity.getText()) ;
        hosp.residence.zip = Integer.parseInt(hospitalZipCode.getText());
        hosp.residence.newCity = hospitalCity.getText();
        hosp.residence.state = hospitalState.getText();
        hosp.setHospWard(Integer.parseInt(hospitalNowards.getText()));
        
        HospitalDirectory.hospDir.add(hosp);
        JOptionPane.showMessageDialog(this, "Person Successfully Added");
        hospDispTable();
        
    }//GEN-LAST:event_hospitalRegisterBtnActionPerformed

    private void hospitalSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalSearchActionPerformed

    private void hospitalUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalUpdateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex1=hospTable.getSelectedRow();
        DefaultTableModel model1 = (DefaultTableModel) hospTable.getModel();
        Hospital selectedHosp=(Hospital)model1.getValueAt(selectedRowIndex1,0);
        selectedHosp.setHospName(hospitalName.getText());
        selectedHosp.setHospLicNo(Integer.parseInt(hospitalLicenseNo.getText()));
        selectedHosp.setHospAddress((hospitalAddress.getText()));
        selectedHosp.residence.setCommunityName(hospitalCommunity.getText()) ;
        selectedHosp.residence.zip = Integer.parseInt(hospitalZipCode.getText());
        selectedHosp.residence.newCity = hospitalCity.getText();
        selectedHosp.residence.state = hospitalState.getText();
        selectedHosp.setHospWard(Integer.parseInt(hospitalNowards.getText()));
        hospDispTable();
    }//GEN-LAST:event_hospitalUpdateBtnActionPerformed

    private void hospitalSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospitalSearchBtnActionPerformed

    public void hospDispTable(){
        DefaultTableModel model1 = (DefaultTableModel) hospTable.getModel();
        model1.setRowCount(0);
        System.out.println("Done");
        for (Hospital h:HospitalDirectory.getHospDir()){
            Object[] row=new Object[8];
            row[0]=h;
            row[1]=h.getHospName();
            row[2]=h.getHospAddress();
            row[3]=h.residence.getCommunityName();
            row[4]=h.residence.getNewCity();
            row[5]=h.residence.getState();
            row[6]=h.residence.getZip();
            row[7]=h.getHospWard();
            model1.addRow(row);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(HospitalRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new HospitalRegistration().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable hospTable;
    private javax.swing.JTextField hospitalAddress;
    private javax.swing.JTextField hospitalCity;
    private javax.swing.JTextField hospitalCommunity;
    private javax.swing.JButton hospitalDeleteBtn;
    private javax.swing.JButton hospitalHomeBtn;
    private javax.swing.JTextField hospitalLicenseNo;
    private javax.swing.JButton hospitalLogoutBtn;
    private javax.swing.JTextField hospitalName;
    private javax.swing.JTextField hospitalNowards;
    private javax.swing.JButton hospitalRegisterBtn;
    private javax.swing.JTextField hospitalSearch;
    private javax.swing.JButton hospitalSearchBtn;
    private javax.swing.JTextField hospitalState;
    private javax.swing.JButton hospitalUpdateBtn;
    private javax.swing.JButton hospitalViewBtn;
    private javax.swing.JTextField hospitalZipCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
