/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package HealthUI;

import Healthmodel.DoctorDirectory;
import Healthmodel.Encounter;
import Healthmodel.EncounterHistory;
import Healthmodel.Patient;
import Healthmodel.PatientDirectory;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chava
 */
public class PatientEncounterDetails extends javax.swing.JPanel {

    /**
     * Creates new form PatientEncounterDetails
     */
    PatientDirectory patientDir;
    DoctorDirectory docDir;
    EncounterHistory encHis;
    public String patientUsername;
    Patient patient=new Patient();
    public PatientEncounterDetails(int patientId) {
        initComponents();
         if(encHis == null){
            this.encHis = new EncounterHistory();
        }
        else{
            this.encHis = encHis;
        }
        
        for(Patient p:PatientDirectory.getPatientDir()){
            if(patientId == p.getPatientId()){
                patient = p;
            }
        }
        patientViewData(patientId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        encounterHistoryViewTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        encounterHistoryLogoutBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        encounterHistoryHomeBtn = new javax.swing.JButton();

        encounterHistoryViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Doctor ID", "Encounter ID", "Date", "Time", "BodyTemp", "BloodPressure", "Symptoms", "Diagnosis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(encounterHistoryViewTable);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        encounterHistoryLogoutBtn.setText("Logout");
        encounterHistoryLogoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encounterHistoryLogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterHistoryLogoutBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        jLabel1.setText("Encounter History");

        encounterHistoryHomeBtn.setText("Home");
        encounterHistoryHomeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        encounterHistoryHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encounterHistoryHomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(encounterHistoryHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                .addComponent(encounterHistoryLogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(encounterHistoryLogoutBtn)
                    .addComponent(encounterHistoryHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 52, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void encounterHistoryLogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterHistoryLogoutBtnActionPerformed
        // TODO add your handling code here:

        LoginFrame newLoginPage = new LoginFrame();
        newLoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_encounterHistoryLogoutBtnActionPerformed

    private void encounterHistoryHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encounterHistoryHomeBtnActionPerformed
        // TODO add your handling code here:

        MainFrame newMainFrame = new MainFrame();
        newMainFrame.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_encounterHistoryHomeBtnActionPerformed
    private void patientViewData(int patientId){
                
        DefaultTableModel model = (DefaultTableModel) encounterHistoryViewTable.getModel();
        model.setRowCount(0);
        
        for(Encounter e: EncounterHistory.getEncHis()){
            
            Object[] row = new Object[8];
            row[0] = e.getEncId();
            row[1] = e.doc.getDocId();
            row[2] = e.getEncDate();
            row[3] = e.getEncTime();
            row[4]=e.getBodyTemperature();
            row[5]=e.getBloodPressure();
            row[6] = e.getSymptoms();
            row[7] =e.getEncDiagnosis();
            model.addRow(row);  
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton encounterHistoryHomeBtn;
    private javax.swing.JButton encounterHistoryLogoutBtn;
    private javax.swing.JTable encounterHistoryViewTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
